# role: k8s
#
# Kubernetes-related tools
---
defrole:
  k8s:
    casks:
      freelens: Kubernetes IDE
      kubeterm: Kubernetes graphical management tool

    ports:
      install:
        dotenv-linter:
        k9s:
        kubie:
        havener:
