# role: llm
#
# The LLM role includes local or remote LLM-related software.
---
defrole:
  llm:
    casks:
      kiro: Agent-centric IDE with spec-driven development
      ollamac: Interact with Ollama models
